apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "creed.labels" . | nindent 4 }}
  name: {{ default $.Release.Name $.Values.name }}-deployment
spec:
  replicas: {{ $.Values.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: {{ $.Values.rollingUpdate.maxSurge }}
      maxUnavailable:  {{ $.Values.rollingUpdate.maxUnavailable }}
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "creed.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "creed.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ default $.Release.Name $.Values.name }}-sa
      containers:
      - image: balamaru/myapp:1.0
        name: creed
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ $.Values.service.targetPort }}
        resources:
          requests:
            memory: {{ $.Values.resources.requests.memory }}
            cpu: {{ $.Values.resources.requests.cpu }}
          limits:
            memory: {{ $.Values.resources.limits.memory }}
            cpu: {{ $.Values.resources.limits.cpu }}